{
 "title": "Weather Data",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "provider",
    "label": "Provider",
    "query": "SELECT DISTINCT(provider) from current_conditions ORDER BY provider ASC;"
   },
   {
    "name": "station",
    "label": "Station",
    "query": "SELECT DISTINCT(station_id) from current_conditions WHERE \"provider\" = '$provider' ORDER BY station_id ASC;"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('30m', \"timestamp\") as time,\n  locf(avg(temperature)) AS \"temperature\"\nFROM\n  current_conditions\nWHERE\n  $__timeFilter(\"timestamp\") AND \"provider\" = '$provider' AND \"station_id\" = '$station'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('5m', \"timestamp\") as time,\n  provider AS provider,\n  locf(avg(feels_like)) AS \"feels_like\"\nFROM\n  current_conditions\nWHERE\n  $__timeFilter(\"timestamp\") AND \"provider\" = '$provider'\nGROUP BY 1,2\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('5m', \"timestamp\") as time,\n  provider AS provider,\n  locf(avg(dew_point)) AS \"dew_point\"\nFROM\n  current_conditions\nWHERE\n  $__timeFilter(\"timestamp\") AND \"provider\" = '$provider'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('30m', \"timestamp\") as time,\n  locf(avg(wind_speed)) AS \"wind_speed\"\nFROM\n  current_conditions\nWHERE\n  $__timeFilter(\"timestamp\") AND \"provider\" = '$provider' AND \"station_id\" = '$station'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('30m', \"timestamp\") as time,\n  locf(avg(wind_gusts)) AS \"wind_gusts\"\nFROM\n  current_conditions\nWHERE\n  $__timeFilter(\"timestamp\") AND \"provider\" = '$provider' AND \"station_id\" = '$station'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('30m', \"timestamp\") as time,\n  locf(avg(humidity)) AS \"humidity\"\nFROM\n  current_conditions\nWHERE\n  $__timeFilter(\"timestamp\") AND \"provider\" = '$provider' AND \"station_id\" = '$station'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('30m', \"timestamp\") as time,\n  locf(avg(wind_bearing)) AS \"wind_bearing\"\nFROM\n  current_conditions\nWHERE\n  $__timeFilter(\"timestamp\") AND \"provider\" = '$provider' AND \"station_id\" = '$station'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('30m', \"timestamp\") as time,\n  locf(avg(abs_pressure)) AS \"abs_pressure\"\nFROM\n  current_conditions\nWHERE\n  $__timeFilter(\"timestamp\") AND \"provider\" = '$provider' AND \"station_id\" = '$station'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('30m', \"timestamp\") as time,\n  locf(avg(rel_pressure)) AS \"rel_pressure\"\nFROM\n  current_conditions\nWHERE\n  $__timeFilter(\"timestamp\") AND \"provider\" = '$provider' AND \"station_id\" = '$station'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Cloud Cover",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('30m', \"timestamp\") as time,\n  locf(avg(cloud_cover)) AS \"cloud_cover\"\nFROM\n  current_conditions\nWHERE\n  $__timeFilter(\"timestamp\") AND \"provider\" = '$provider' AND \"station_id\" = '$station'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('30m', \"timestamp\") as time,\n  locf(avg(uv_index)) AS \"uv_index\"\nFROM\n  current_conditions\nWHERE\n  $__timeFilter(\"timestamp\") AND \"provider\" = '$provider' AND \"station_id\" = '$station'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Visibility",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('30m', \"timestamp\") as time,\n  locf(avg(visibility)) AS \"visibility\"\nFROM\n  current_conditions\nWHERE\n  $__timeFilter(\"timestamp\") AND \"provider\" = '$provider' AND \"station_id\" = '$station'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Ozone",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('30m', \"timestamp\") as time,\n  locf(avg(ozone)) AS \"ozone\"\nFROM\n  current_conditions\nWHERE\n  $__timeFilter(\"timestamp\") AND \"provider\" = '$provider' AND \"station_id\" = '$station'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Solar Radiation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('30m', \"timestamp\") as time,\n  locf(avg(solar_rad)) AS \"solar_rad\"\nFROM\n  current_conditions\nWHERE\n  $__timeFilter(\"timestamp\") AND \"provider\" = '$provider' AND \"station_id\" = '$station'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}